language: rust

os:
  - linux
  - osx

rust:
  - stable
  - beta
  - nightly

jobs:
  include:
    - stage: lint
      os: linux
      rust: stable
      install:
        - rustup component add clippy
      script:
        - cargo clippy --all -- --deny clippy::all

    - stage: format
      os: linux
      rust: stable
      install:
        - rustup component add rustfmt
      script:
        - cargo fmt --all -- --check

    - stage: deploy
      branches:
        only:
          - master
      if: tag IS present AND fork = false
      os:
        - linux
        - osx
      rust: stable
      script:
        - if [ "$TRAVIS_OS_NAME" = "linux" ]; then export EXECUTABLE_NAME=human-x86_64-unknown-linux-gnu; fi
        - if [ "$TRAVIS_OS_NAME" = "osx" ]; then export EXECUTABLE_NAME=human-x86_64-apple-darwin; fi
        - cargo build --release
        - strip -s target/release/human
        - mv target/release/human target/release/$EXECUTABLE_NAME
      deploy: &releases
        provider: releases
        api_key: $GITHUB_TOKEN
        file: "target/release/$EXECUTABLE_NAME"
        skip_cleanup: true
        on:
          tags: true
