[package]
name = "human"
version = "1.0.0"
authors = ["Jan Baudisch <dev@baudisch.xyz>"]
description = "Converts a numeric litaral into an humand-readable format."
edition = "2018"

[dependencies]

[profile.release]
lto = true
codegen-units = 1
